export interface ElementTransform {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
  zIndex: number;
}

export type IncentivesLayoutConfig = Record<string, ElementTransform>;

export const defaultTransform: ElementTransform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  zIndex: 10,
};

// AUTO-GENERATED BY VISUAL EDITOR
export const incentivesLayout: IncentivesLayoutConfig = {
  "defaultTransform": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 1
  },
  "certificate-image": {
    "x": 38,
    "y": 25,
    "scale": 1.5,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "certificate-label": {
    "x": 58,
    "y": 36,
    "scale": 1.1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "pronite-pass-image": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "pronite-pass-label": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "merchandise-image": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "merchandise-label": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "opportunities-image": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  },
  "opportunities-label": {
    "x": 0,
    "y": 0,
    "scale": 1,
    "rotation": 0,
    "opacity": 1,
    "zIndex": 10
  }
};
